import type { NextPage } from 'next'
import Head from 'next/head'
import ChurrasTemplate from '../modules/churras/components/ChurrasTemplate'
import ChurrasProvider from '../modules/churras/contexts/ChurrasContext'
import ToastProvider from '../shared/providers/Toast'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Churras Trinca</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <ToastProvider>
        <ChurrasProvider>
          <ChurrasTemplate/>
        </ChurrasProvider>
      </ToastProvider>
    </div>

  )
}

export default Home
